[package]
name = "pyo3_ref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "pyo3_ref"


[dependencies]
noodles = {version = "0.52.0", features=["vcf"]}
pyo3 = {version="0.19.2", features=["auto-initialize", "abi3", "abi3-py37"]}

[features]
extension-module=["pyo3/extension-module"]
default=["extension-module"]
