[package]
name = "pyo3_ref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyo3_ref"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version="0.19.0", features=["auto-initialize"]}
